# 启动本地服务配置
server:
  port: 3000
  origin: localhost

# 数据库配置
db:
  type: 'mysql' # 数据库类型
  port: 3306 # 端口号
  database: 'testdb' # 数据库名

# swagger接口文档配置
swagger:
  enable: true # 是否打开swagger接口文档

# jwt配置
jwt:
  expiresIn: 3600
